### ISSUE TITLE
Pinned tabs are hidden

### ISSUE THREAD

**Issue by nhermosilla14** [FirefoxCSSThemers/Monterey-Fox#2]
It's just that, it does not display pinned tabs as it should, it just hides them (although you can still access them via ctrl-tab).

**Comment by alfaaarex** [comment]
Hi Nicolas,
The theme is still under development. We are aware of the fact that there are such issues with tabs since achieving such a goal is pretty tedious. Moreover, if you want to help us out, just change the code and make a PR. We will review it and merge the PR.
Regards,
@AlfarexGuy2019 
Founder of Firefox CSS Themers

**Comment by nhermosilla14** [comment]
I will try to fix it, but since I don't have experience with Firefox
theming, can't really be sure how well that will go. Anyway, it's already a
great theme, thanks for all the hard work.

**Comment by alfaaarex** [comment]
You're welcome
